apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:0oe+bzHnd0o=,iv:Nz5k/lfwP/xQZdFuTphKiJQUdbDR2Xss1+ReTcJKiqg=,tag:pRPuFlRM5WtUYzgmFF94cA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:E4eAM6jICqenfDRQ,iv:mHFF8iORj7dCrG5i2KVN75ElD/9bgl4NKoc/pmG90PA=,tag:dlf1Y1aVDz2GD2DKkhQRZA==,type:str]
kind: Secret
metadata:
    name: super-user-creds
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dGlCdGQxTlFmZjIxKzdj
            ZXMzbnJrUEhnVHZZMmlrZTZ0b3ZKdTdiVmw4Cmw2Nk5oYkZ6cVZ0ZkMyWFJFNnZS
            MmF2OXhlM01meVlmak9ZSUZKTFREQmsKLS0tIE5XZXVrSTl2Q2RkeFlsRlNvYWt2
            czJhcllLbnY5NkltS0p1aGd3VVQwUWcKgCqJt5BoaCRTsk/MwT8gizUubzlpIVVd
            Iarqk0UhaXrVWRwmHjLMpFvODdB8Yr1ZI5drOXTcKdjODcxxhTx6Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T19:03:21Z"
    mac: ENC[AES256_GCM,data:vYYEB/XqvAPA9mh45ZhHJ0r7VuiPFGH2b93tRy2Vh+WlWd62FhbtYNrKCUgHJLGo6OJc4KZ9MqFZx4BPjjS6LlqxkpAbC7qNFIlwNoXsnvBvIUCJOnmhUh/c9XtlZXej1dze/DrGUJCynhTP5hHRVSmCdf6p3GPLa6krdWyxYpw=,iv:vGXVyZO3nM/ifhbWw9PPUJl7IScYf2yv7v7qbaFLcFg=,tag:NzxC4jXUZPSwOe4wH/lXfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
